<?php
require_once '../includes/session.php';
require_once '../config/database.php';

// Check admin session
checkAdminSession();

// Get report type from query string
$type = isset($_GET['type']) ? $_GET['type'] : 'weekly';

// Set date range based on report type
$start_date = date('Y-m-d');
$end_date = date('Y-m-d');

switch ($type) {
    case 'weekly':
        $start_date = date('Y-m-d', strtotime('-7 days'));
        break;
    case 'monthly':
        $start_date = date('Y-m-01');
        $end_date = date('Y-m-t');
        break;
    case 'yearly':
        $start_date = date('Y-01-01');
        $end_date = date('Y-12-31');
        break;
    default:
        header("Location: dashboard.php");
        exit();
}

try {
    // Get bookings for the date range
    $stmt = $pdo->prepare("
        SELECT 
            b.*,
            r.room_number,
            rt.name as room_type,
            rt.price as room_price,
            c.first_name,
            c.last_name,
            c.email,
            c.phone,
            CASE 
                WHEN b.confirmed_by IS NOT NULL THEN a.username 
                ELSE NULL 
            END as confirmed_by_name
        FROM bookings b
        JOIN rooms r ON b.room_id = r.id
        JOIN room_types rt ON r.room_type_id = rt.id
        JOIN customers c ON b.customer_id = c.id
        LEFT JOIN admin a ON b.confirmed_by = a.id
        WHERE (b.check_in BETWEEN ? AND ? OR b.check_out BETWEEN ? AND ?)
        AND b.status != 'cancelled'
        ORDER BY b.check_in DESC
    ");
    $stmt->execute([$start_date, $end_date, $start_date, $end_date]);
    $bookings = $stmt->fetchAll();

    // Calculate statistics
    $total_bookings = count($bookings);
    $total_revenue = array_sum(array_column($bookings, 'total_amount'));
    $confirmed_bookings = count(array_filter($bookings, fn($b) => $b['status'] === 'confirmed'));
    $completed_bookings = count(array_filter($bookings, fn($b) => $b['status'] === 'completed'));

    // Get admin info
    $stmt = $pdo->prepare("SELECT username FROM admin WHERE id = ?");
    $stmt->execute([$_SESSION['admin_id']]);
    $admin = $stmt->fetch();

} catch (Exception $e) {
    die("Error generating report: " . $e->getMessage());
}

// Helper function to get status badge class
function getStatusBadgeClass($status) {
    switch ($status) {
        case 'pending':
            return 'bg-warning';
        case 'confirmed':
            return 'bg-success';
        case 'checked_in':
            return 'bg-primary';
        case 'checked_out':
            return 'bg-info';
        case 'cancelled':
            return 'bg-danger';
        default:
            return 'bg-secondary';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo ucfirst($type); ?> Report - Hotel Management System</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        @media print {
            .no-print {
                display: none !important;
            }
            .table {
                width: 100% !important;
                font-size: 12px !important;
            }
            .container {
                width: 100% !important;
                max-width: none !important;
                padding: 0 !important;
                margin: 0 !important;
            }
        }
        .report-header {
            border-bottom: 2px solid #dee2e6;
            margin-bottom: 2rem;
            padding-bottom: 1rem;
        }
        .stats-card {
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
            transition: transform 0.3s;
        }
        .stats-card:hover {
            transform: translateY(-5px);
        }
        .bookings-table {
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body class="bg-light">
    <div class="container py-5">
        <!-- Report Header -->
        <div class="report-header">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h1 class="mb-0"><?php echo ucfirst($type); ?> Report</h1>
                    <p class="text-muted mb-0">
                        <?php echo date('F d, Y', strtotime($start_date)); ?> - 
                        <?php echo date('F d, Y', strtotime($end_date)); ?>
                    </p>
                </div>
                <div class="col-md-6 text-md-end">
                    <p class="mb-0">Generated by: <?php echo htmlspecialchars($admin['username']); ?></p>
                    <p class="text-muted mb-0">Generated on: <?php echo date('F d, Y H:i:s'); ?></p>
                </div>
            </div>
        </div>

        <!-- Statistics Cards -->
        <div class="row mb-4">
            <div class="col-md-3">
                <div class="card stats-card bg-primary text-white">
                    <div class="card-body">
                        <h6 class="card-title">Total Bookings</h6>
                        <h3 class="card-text mb-0"><?php echo $total_bookings; ?></h3>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card stats-card bg-success text-white">
                    <div class="card-body">
                        <h6 class="card-title">Confirmed Bookings</h6>
                        <h3 class="card-text mb-0"><?php echo $confirmed_bookings; ?></h3>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card stats-card bg-info text-white">
                    <div class="card-body">
                        <h6 class="card-title">Completed Bookings</h6>
                        <h3 class="card-text mb-0"><?php echo $completed_bookings; ?></h3>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card stats-card bg-warning text-white">
                    <div class="card-body">
                        <h6 class="card-title">Total Revenue</h6>
                        <h3 class="card-text mb-0">₱<?php echo number_format($total_revenue, 2); ?></h3>
                    </div>
                </div>
            </div>
        </div>

        <!-- Bookings Table -->
        <div class="card bookings-table">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h4 class="card-title mb-0">Booking Details</h4>
                    <button onclick="window.print()" class="btn btn-primary no-print">
                        <i class="fas fa-print me-2"></i>Print Report
                    </button>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Booking ID</th>
                                <th>Guest</th>
                                <th>Room</th>
                                <th>Check-in</th>
                                <th>Check-out</th>
                                <th>Amount</th>
                                <th>Status</th>
                                <th>Confirmed By</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($bookings as $booking): ?>
                                <tr>
                                    <td><?php echo $booking['id']; ?></td>
                                    <td>
                                        <div><?php echo htmlspecialchars($booking['first_name'] . ' ' . $booking['last_name']); ?></div>
                                        <small class="text-muted"><?php echo htmlspecialchars($booking['email']); ?></small>
                                    </td>
                                    <td>
                                        <div>Room #<?php echo htmlspecialchars($booking['room_number']); ?></div>
                                        <small class="text-muted"><?php echo htmlspecialchars($booking['room_type']); ?></small>
                                    </td>
                                    <td><?php echo date('Y-m-d H:i', strtotime($booking['check_in'])); ?></td>
                                    <td><?php echo date('Y-m-d H:i', strtotime($booking['check_out'])); ?></td>
                                    <td>₱<?php echo number_format($booking['amount'], 2); ?></td>
                                    <td>
                                        <span class="badge <?php echo getStatusBadgeClass($booking['status']); ?>">
                                            <?php echo ucfirst($booking['status']); ?>
                                        </span>
                                    </td>
                                    <td><?php echo $booking['confirmed_by_name'] ?? 'N/A'; ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Back Button -->
        <div class="text-center mt-4 no-print">
            <a href="dashboard.php" class="btn btn-secondary">
                <i class="fas fa-arrow-left me-2"></i>Back to Dashboard
            </a>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
